### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by 404UserNotFound** [LestaD/SourceEngine2007#1]
- Nevermind, I figured out that the code I was looking at was TF2 Invasion-era -

**Comment by LestaD** [comment]
@404UserNotFound I don't know, sorry

**Comment by 404UserNotFound** [comment]
I edited the original question and answered it for you. It's Team Fortress 2, but not the TF2 we have today. It's the old "Aliens" vs "Humans" development stage of Team Fortress 2 called the "Invasion" phase, detailed in this article on the TF2 Wiki: https://wiki.teamfortress.com/wiki/Invasion

Upon reviewing the code, I notice many similarities between this "Invasion" phase of development of TF2 and another Source engine game called "Nuclear Dawn". Both games feature a "commander" class that can build support buildings, there's mech-like "walker" vehicles alongside human vehicles like wagons, flatbeds, etc.
